//
//  AppAssets.swift
//  ecommerce_swiftui
//
//  Created by Ahmed Galal on 13/09/2025.
//

class AppAssets {
    static let splashBackground = "background"
    static let nameApp = "app_logo_black"
    static let nameAppWhite = "app_logo_white"
    static let appLogo = "app_logo"
    static let noImage = "noimage"
    
    static let bgOnBoarding = "bgonboarding"
    static let mailFo = "mailfo"
    static let onBo1 = "q1"
    static let box = "box"
    
    static let onBo2 = "q2"
    static let onBo3 = "q3"
    static let done = "Done"
    static let bgMain = "bgmain"
    static let iconFeather = "IconFeather-shopping-cart"
    static let iconAwesome = "IconAwesome-shopping-bag"
    static let iconMapBeauty = "IconMap-beauty-salon"
    static let iconOutline = "outline"
    static let heartSelect = "heart1"
    static let heart = "heart"
    static let heart2 = "heart2"
    static let heart4 = "heart4"
    static let mail = "mail"
    static let ballSelect = "ballSelect"
    static let ball = "bell"
    static let sort = "sort"
    static let filter = "filtter"
    static let noInternet = "nointernet"
    static let person = "person"
    static let userProfile = "user"
    static let markerDown = "markerdown"
    static let doneCoupon = "donecoupon0"
    static let usedCoupon = "usedcoupon0"
    static let errorCoupon = "errorcoupon0"
    static let note = "note"
    static let cart = "trolley-cart"
    static let cart1 = "trolley-cart1"
    static let cart3 = "trolley-cart3"
    
    
    static let favoriteSelect = "Iconmaterial-favorite"
    static let favorite = "Iconmaterial-favorite-border"
    static let userSelect = "fi-rr-user1"
    static let bellActive1 = "bellactive1"
    static let bellActive2 = "bellactive2"
    
    static let orderSelect = "fi-rr-subtitles2"
    static let order = "fi-rr-subtitles"
    static let homeSelect = "fi-rr-home1"
    static let home = "fi-rr-home"
    static let notification = "notification"
    static let notificationSelect = "notification1"
    static let vector = "Vector14"
    static let discount = "discount"
    static let arrowRight = "arrowright"
    static let arrowLeft = "arrowleft"
    static let clothes = "clothes"
    static let placeholder = "Placeholder"
    static let placeholder2 = "Placeholder-2"
    static let menuLLeft = "menu-left"
    static let languages = "languages"
    static let logout = "logout"
    static let logoutAr = "logoutar"
    static let ourTeam = "ourteam"
    static let edit = "edit"
    static let contactus = "contactus"
    static let about = "about"
    static let sale = "sale"
    static let wishlist = "wishlist"
    
    static let menuLeftSelect = "menu-left1"
    static let delete = "delete"
    static let arrival = "arrival"
    static let calling = "calling"
    static let ic_right = "ic_right"
    static let ic_arabic = "ic_arabic"
    static let ic_english = "ic_english"
    static let order_ok = "order_ok"
    static let notification_payment = "ic_payment"
    static let notification_Accept = "ic_accept"
    static let notification_promo = "icons-promo"
    static let order_no = "order_no"
    static let order_shipped = "order_shipped"
    
    static let iconEmail = "mail"
    static let iconLock = "lock"
    static let user = "Profile"
    static let map = "map"
    static let shop = "shop"
    static let markerGrey = "markerdown"
    static let markerWhite = "markerdownwhite"
    static let phone = "phone"
    static let key = "key"
    
    static let menuHome = "aa"
    static let menuAbout = "about-variant"
    static let menuOffers = "bag-check-1"
    static let menuCall = "headphones-line"
    static let menuFav = "heart-line"
    static let menuProfile = "id-badge-line"
    static let menuTerms = "lightbulb-line"
    static let menuLogout = "log-out-outline"
    static let menuLogin = "log-out-outline-1"
    static let menuSend = "send"
    static let deleteGrey = "deletegrey"
    static let deleteRed = "deletered"
    
    static let bagGrey = "bag-check"
    static let bagWhite = "bag-check-2"
    static let bellGrey = "bell-1"
    static let bellWhite = "bell"
    static let homeGrey = "Home"
    static let homeWhite = "Home-1"
    static let moreGrey = "More"
    static let moreWhite = "More-1"
    static let saleGray = "saleGray"
    static let saleWhite = "saleWhite"
    static let userGray = "userGray"
    static let userWhite = "userWhite"
    static let discountGray = "discount-gray"
    static let discountWhite = "discount-white"
    
    static let login = "login"
    static let hourglass = "time_passing"
    
    static let cursorHand = "cursor-hand-click-line"
    static let exclamationMark = "exclamation-mark"
    
    static let maintenance="under-maintenance"
    static let arabic = "saudi-arabia"
    static let english = "united-kingdom"
    
    static let starGray = "starwhite"
    static let starYellow = "staryellow"
    
    static let markerOnMap = "mapmarker"
    static let building = "building"
    static let visa = "card"
    static let cash = "money"
    static let wallet = "wallet"
    static let language = "language"
    
    static let facebook = "facebook"
    static let whatsapp = "whatsapp"
    static let instagram = "instagram"
    
    static let asterisk = "asterisk"
    static let offerTag = "offer-tag"
}
